name = "DarkScanner"
pages_build_output_dir = "./svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "darkscanner"
database_id = "41ac7730-d737-4f27-8a89-ef9b65a3b49b"
